version: '3.7'


volumes:
  prometheus_data: { }
  grafana_data: { }

networks:
  front-tier:
  back-tier:

services:
  prometheus:
    image: prom/prometheus:v2.39.1
    container_name: webinar-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    restart: unless-stopped
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    networks:
      - back-tier


  grafana:
    image: grafana/grafana-oss:9.2.0
    container_name: webinar-grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    env_file:
      - ./grafana/config
    networks:
      - back-tier
      - front-tier

  alertmanager:
    image: prom/alertmanager:v0.24.0
    container_name: webinar-alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    restart: unless-stopped
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    container_name: webinar-cadvisor
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - back-tier