# Spring properties
spring:
  datasource:
    url: jdbc:h2:mem:smart_mobility_db
    username: sa
    password: jordan23
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        ddl-auto: create-drop
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

# Server properties
server:
  port: 8090

# Application internal properties
smart-mobility:
  http-client:
    payment-application-url: localhost:8091