# Spring properties
spring:
  datasource:
    url: jdbc:h2:mem:smart_mobility_db
    username: sa
    password: jordan23
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: false
        ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

# Actuator
#  TODO_STAGE_1 Add prometheus endpoint to actuator
management:
  endpoints:
    web:
      exposure:
        include: health

# Server properties
server:
  port: 8090

# Application internal properties
smart-mobility:
  http-client:
    payment-application-url: http://payment:8091
    network-latency-millis: 2000