# Spring properties
spring:
  datasource:
    url: jdbc:h2:mem:payment_db
    username: sa
    password: jordan23
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: false
        ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health

# Server properties
server:
  port: 8091

# Application internal properties
payment:
  confirmation:
    range: 100
    threshold: 50
  http-client:
    smart-mobility-application-url: http://smart-mobility:8090
    network-latency-millis: 2000
